### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-7#1]
- [x] nie musisz deklarowac dodatkowej zmiennej `x`
- [x] teraz dorzucasz do tablicy 'Mariana' jako zwykly string, a w zmiennej `newName` mogloby byc inne imie, wiec lepiej dorzucac, to co jest w zmiennej

**Comment by JoannaKu** [comment]
nie jestem pewna czy dobrze to zmieniłam, ale w konsoli działa :)

**Comment by michal-bootcamp** [comment]
super, dodaj jeszcze srednik w linii 7 i te linie:
`allNames = allNames.push(newName);`
mozesz skrocic do:
`allNames.push(newName);`

**Comment by JoannaKu** [comment]
poprawione :)
